// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_HUOFreLwivf7Fc_SuGQVntOYcDa-Es',
    appId: '1:938415700918:web:bf5179be0ab97fffba5f17',
    messagingSenderId: '938415700918',
    projectId: 'apnichat-24c39',
    authDomain: 'apnichat-24c39.firebaseapp.com',
    storageBucket: 'apnichat-24c39.firebasestorage.app',
    measurementId: 'G-GKWBM4TM6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgO3cg9rXjItWhkzQajjAic1a9ohw0kJA',
    appId: '1:938415700918:android:905e59428fd3b41cba5f17',
    messagingSenderId: '938415700918',
    projectId: 'apnichat-24c39',
    storageBucket: 'apnichat-24c39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsNHFx02V_1JJv-h8tFF8fQhqIQRU6-yI',
    appId: '1:938415700918:ios:b0cb8928f658630aba5f17',
    messagingSenderId: '938415700918',
    projectId: 'apnichat-24c39',
    storageBucket: 'apnichat-24c39.firebasestorage.app',
    iosBundleId: 'com.example.apnichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsNHFx02V_1JJv-h8tFF8fQhqIQRU6-yI',
    appId: '1:938415700918:ios:b0cb8928f658630aba5f17',
    messagingSenderId: '938415700918',
    projectId: 'apnichat-24c39',
    storageBucket: 'apnichat-24c39.firebasestorage.app',
    iosBundleId: 'com.example.apnichat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-_HUOFreLwivf7Fc_SuGQVntOYcDa-Es',
    appId: '1:938415700918:web:9b5f7fd5290c6bf8ba5f17',
    messagingSenderId: '938415700918',
    projectId: 'apnichat-24c39',
    authDomain: 'apnichat-24c39.firebaseapp.com',
    storageBucket: 'apnichat-24c39.firebasestorage.app',
    measurementId: 'G-LP2WYSYDR9',
  );
}
